# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruote-dm}
  s.version = "2.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Mettraux"]
  s.date = %q{2010-02-08}
  s.description = %q{datamapper storage for ruote 2.1}
  s.email = %q{jmettraux@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.txt",
     "CREDITS.txt",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "TODO.txt",
     "lib/ruote-dm.rb",
     "lib/ruote/dm/storage.rb",
     "lib/ruote/dm/version.rb",
     "ruote-dm.gemspec",
     "test/integration_connection.rb",
     "test/test.rb"
  ]
  s.homepage = %q{http://github.com/jmettraux/ruote-dm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ruote}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{datamapper storage for ruote 2.1}
  s.test_files = [
    "test/test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruote>, [">= 2.1.6"])
      s.add_runtime_dependency(%q<dm-core>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<ruote>, [">= 2.1.6"])
      s.add_dependency(%q<dm-core>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruote>, [">= 2.1.6"])
    s.add_dependency(%q<dm-core>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

